-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Tickers"
(
    ticker_id integer,
    ticker text,
    PRIMARY KEY (ticker_id)
);

CREATE TABLE IF NOT EXISTS public."Companies"
(
    company_id integer,
    symbol_id integer,
    asset_type text,
    name text,
    description text,
    exchange text,
    currency text,
    country text,
    sector text,
    industry text,
    PRIMARY KEY (company_id)
);

CREATE TABLE IF NOT EXISTS public.company_numeric_data
(
    comp_num_id integer,
    comp_id integer,
    div_per_share numeric,
    "div_Yield" numeric,
    "52_week_high" numeric,
    "52_week_low" numeric,
    "50_day_mov_avg" numeric,
    "200_day_mov_avg" numeric,
    div_date date,
    ex_div_date date,
    PRIMARY KEY (comp_num_id)
);

CREATE TABLE IF NOT EXISTS public.hist_data
(
    hist_id integer,
    ticker_id integer,
    "timestamp" date,
    open numeric,
    high numeric,
    low numeric,
    close numeric,
    volume numeric,
    PRIMARY KEY (hist_id)
);

CREATE TABLE IF NOT EXISTS public.models
(
    models_id integer,
    ticker_id integer,
    model bytea,
    PRIMARY KEY (models_id)
);

CREATE TABLE IF NOT EXISTS public.predictions
(
    pred_id integer,
    ticker_id integer,
    model_id integer,
    "timestamp" date,
    open numeric,
    high numeric,
    low numeric,
    close numeric,
    volume numeric,
    is_predicted boolean,
    PRIMARY KEY (pred_id)
);

ALTER TABLE IF EXISTS public."Companies"
    ADD FOREIGN KEY (symbol_id)
    REFERENCES public."Tickers" (ticker_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.company_numeric_data
    ADD FOREIGN KEY (comp_id)
    REFERENCES public."Companies" (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.hist_data
    ADD FOREIGN KEY (ticker_id)
    REFERENCES public."Tickers" (ticker_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.models
    ADD FOREIGN KEY (ticker_id)
    REFERENCES public."Tickers" (ticker_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.predictions
    ADD FOREIGN KEY (ticker_id)
    REFERENCES public."Tickers" (ticker_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.predictions
    ADD FOREIGN KEY (model_id)
    REFERENCES public.models (models_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;